DROP TABLE IF EXISTS Employment_Information;
CREATE TABLE Employment_Information(
    ID VARCHAR(10),
    EID VARCHAR(10),
    NAME VARCHAR(30),
    LOCAL VARCHAR(30),
    POSTION VARCHAR(30),
    DESCRIPTION VARCHAR(100),
    BENEFIT VARCHAR(100),
    SALARY VARCHAR(30),
    REQUIREMENT VARCHAR(100),
    QUANTITY INT,
    PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS Individual;
CREATE TABLE Individual(
    IID VARCHAR(10),
    INAME VARCHAR(30),
    ILOCAL VARCHAR(30),
    PRIMARY KEY(IID),
    FOREIGN KEY (IID) REFERENCES Employment_Information(ID)
);

DROP TABLE IF EXISTS Organization;
CREATE TABLE Organization(
    CID VARCHAR(10),
    CNAME VARCHAR(30),
    CLOCAL VARCHAR(30),
    PRIMARY KEY (CID),
    FOREIGN KEY (CID) REFERENCES Employment_Information(ID)
);