CREATE TABLE Employment_Information(
    EID INT,
    ENAME VARCHAR(30),
    PRIMARY KEY(EID)
);

CREATE TABLE Individual(
    IID INT,
    INAME VARCHAR(30),
    ILOCAL VARCHAR(30),
    IPOSTION VARCHAR(30),
    IDESCRIPTION VARCHAR(100),
    IBENEFIT VARCHAR(100),
    ISALARY VARCHAR(30),
    IREQUIREMENT VARCHAR(100),
    QUANTITY INT,
    PRIMARY KEY (IID),
    FOREIGN KEY (IID) REFERENCES Employment_Information(EID)
);

CREATE TABLE Company(
    CID INT,
    CNAME VARCHAR(30),
    CLOCAL VARCHAR(30),
    CPOSITION VARCHAR(30),
    CDESCRIPTION VARCHAR(100),
    CBENEFIT VARCHAR(100),
    CSALARY VARCHAR(30),
    CREQUIREMENT VARCHAR(100),
    PRIMARY KEY (CID),
    FOREIGN KEY (CID) REFERENCES Employment_Information(EID)
);

CREATE TABLE Company_Information(
    CIID INT,
    CINAME VARCHAR(30),
    ADDRESS VARCHAR(30),
    PRIMARY KEY (CIID),
    FOREIGN KEY (CIID) REFERENCES Company(CID)
);